name: Code-style

on:
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install clang tools
      run: |
        sudo apt-get update
        sudo apt-get install -y clang clang-tools bear

    - name: Check clang-format
      run: make check-format

    - name: Run clang-tidy
      run: make tidy
